### PR TITLE
Update troll.sh

### PR DESCRIPTION
**Pull request by strongpapazola**
Fix Read Fitur

### CODE REVIEW

**Comment by strongpapazola** [comment]
Kapan kapan kita bikin tools bareng ya hackbae... :D

**Comment by hacBae** [comment]
Ol

**Comment by hacBae** [comment]
Ok

**Comment by ahmaddenideni** [comment]
Assalamualaikum wr.wb

**Comment by HackerVillain** [comment]
Ok

**Comment by fismmmpro** [comment]
Saya pen belajar ka hehe

**Review by baracodam — COMMENTED** [review]
Gg

**Comment by bangadd** [comment]
Ajarai sya dunk..😊

**Pull request closed without merging**
